export const GET_CONTACTS = "GET_CONTACTS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const ADD_CONTACT = "ADD_CONTACT";
export const GET_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "ADD_CONTACT";
